backend:
  name: github
  repo: getpackup/packup-monorepo
  api_root: https://api.github.com
  branch: main
  commit_messages:
    create: 'Create {{collection}} “{{slug}}”'
    update: 'Update {{collection}} “{{slug}}”'
    delete: 'Delete {{collection}} “{{slug}}”'
    uploadMedia: '[skip ci] Upload “{{path}}”'
    deleteMedia: '[skip ci] Delete “{{path}}”'

site_url: https://getpackup.com
logo_url: https://getpackup.com/icons/icon-72x72.png

media_library:
  name: cloudinary
  config:
    cloud_name: getpackup
    api_key: 342326781417379

media_folder: 'apps/marketing/public/images'
public_folder: 'apps/marketing/public'

collections:
  - name: 'blog'
    editor:
      preview: true
    label: 'Blog'
    folder: 'apps/marketing/content/blog'
    create: true
    slug: '{{year}}-{{month}}-{{day}}-{{slug}}'
    fields:
      - { label: 'Template Key', name: 'templateKey', widget: 'hidden', default: 'blog-post' }
      - { label: Title, name: title, widget: string }
      - { label: 'Publish Date', name: date, widget: datetime }
      - { label: Description, name: description, widget: text }
      - { label: 'Featured Post', name: featuredpost, widget: boolean, required: false }
      - { label: 'Featured Image', name: featuredimage, widget: image }
      - { label: Body, name: body, widget: markdown }
      - { label: Tags, name: tags, widget: list, required: false }

  - name: 'pages'
    label: 'Pages'
    files:
      - file: 'apps/marketing/content/index.md'
        label: 'Home Page'
        name: 'index'
        editor:
          preview: true
        fields:
          - { label: 'Template Key', name: 'templateKey', widget: 'hidden', default: 'index-page' }
          - { label: Title, name: title, widget: string }
          - { label: HeroImage, name: heroImage, widget: image }
          - { label: HeroMobileImage, name: mobileHeroImage, widget: image }
          - { label: HeroHeading, name: heroHeading, widget: string }
          - {
              label: HeroHeadingTypewriter,
              name: typewriterList,
              widget: list,
              fields: [{ label: text, name: text, widget: string }],
            }
          - { label: HeroSubheading, name: heroSubheading, widget: string }
          - { label: HeroCTALink, name: heroCTALink, widget: string }
          - { label: HeroCTAText, name: heroCTAText, widget: string }
          - {
              label: Mainpitch,
              name: mainpitch,
              widget: object,
              fields:
                [
                  { label: Heading, name: heading, widget: string },
                  { label: Subheading, name: subheading, widget: string },
                  { label: Text, name: text, widget: string },
                  { label: Image, name: image, widget: image },
                ],
            }
          - {
              label: SecondPitch,
              name: secondpitch,
              widget: object,
              fields:
                [
                  { label: Heading, name: heading, widget: string },
                  { label: Subheading, name: subheading, widget: string },
                  { label: Text, name: text, widget: string },
                  { label: Image, name: image, widget: image },
                ],
            }
          - {
              label: ThirdPitch,
              name: thirdpitch,
              widget: object,
              fields:
                [
                  { label: Heading, name: heading, widget: string },
                  { label: Subheading, name: subheading, widget: string },
                  { label: Text, name: text, widget: string },
                  { label: Image, name: image, widget: image },
                ],
            }
          - {
              label: FourthPitch,
              name: fourthpitch,
              widget: object,
              fields:
                [
                  { label: Heading, name: heading, widget: string },
                  { label: Subheading, name: subheading, widget: string },
                  { label: Text, name: text, widget: string },
                  { label: Image, name: image, widget: image },
                ],
            }
          - {
              label: 'Testimonial',
              name: testimonials,
              widget: list,
              fields:
                [
                  { label: Quote, name: quote, widget: string },
                  { label: Author, name: author, widget: string },
                  { label: Location, name: location, widget: string },
                  { label: Avatar, name: avatar, widget: image },
                ],
            }

      - file: 'apps/marketing/content/about.md'
        label: 'About'
        name: 'about'
        editor:
          preview: true
        fields:
          - { label: 'Template Key', name: 'templateKey', widget: 'hidden', default: 'about-page' }
          - { label: Title, name: title, widget: string }
          - { label: Body, name: body, widget: markdown }
          - { label: HeroImage, name: heroImage, widget: image }
      - file: 'apps/marketing/content/contact.md'
        label: 'Contact'
        name: 'contact'
        editor:
          preview: true
        fields:
          - {
              label: 'Template Key',
              name: 'templateKey',
              widget: 'hidden',
              default: 'contact-page',
            }
          - { label: Title, name: title, widget: string }
          - { label: Body, name: body, widget: markdown }
          - { label: HeroImage, name: heroImage, widget: image }
      - file: 'apps/marketing/content/blog/index.md'
        label: 'Blog'
        name: 'blog'
        fields:
          - {
              label: 'Template Key',
              name: 'templateKey',
              widget: 'hidden',
              default: 'blog-index-page',
            }
          - { label: Title, name: title, widget: string }
          - { label: Body, name: body, widget: markdown }
          - { label: HeroImage, name: heroImage, widget: image }
      - file: 'apps/marketing/content/tags/index.md'
        label: 'Tags'
        name: 'tags'
        fields:
          - {
              label: 'Template Key',
              name: 'templateKey',
              widget: 'hidden',
              default: 'tags-index-page',
            }
          - { label: Title, name: title, widget: string }
          - { label: Body, name: body, widget: markdown }
          - { label: HeroImage, name: heroImage, widget: image }
      - file: 'apps/marketing/content/terms.md'
        label: 'Terms'
        name: 'terms'
        fields:
          - { label: 'Template Key', name: 'templateKey', widget: 'hidden', default: 'terms' }
          - { label: Title, name: title, widget: string }
          - { label: HeroImage, name: heroImage, widget: image }
          - { label: Body, name: body, widget: markdown }
      - file: 'apps/marketing/content/privacy.md'
        label: 'Privacy'
        name: 'privacy'
        fields:
          - { label: 'Template Key', name: 'templateKey', widget: 'hidden', default: 'privacy' }
          - { label: Title, name: title, widget: string }
          - { label: Body, name: body, widget: markdown }
      - file: 'apps/marketing/content/links.md'
        label: 'Links Page'
        name: 'links'
        editor:
          preview: true
        fields:
          - { label: 'Template Key', name: 'templateKey', widget: 'hidden', default: 'links-page' }
          - {
              label: LinksList,
              name: linksList,
              widget: list,
              summary: '{{fields.linkText}}',
              label_singular: 'New Link',
              fields:
                [
                  {
                    label: LinkURL,
                    name: linkUrl,
                    widget: string,
                    hint: 'For internal links (pages on our website, like blogs), dont include the domain name, just start with the / after getpackup.com',
                  },
                  { label: LinkText, name: linkText, widget: string },
                  { label: ThumbnailImage, name: thumbnail, widget: image },
                ],
            }
